#!/bin/sh

test $# -eq 0 && { echo "Usage: [number] [message]" 1>&2; exit 1; }
number=$1; 
shift; 
#msg="$*";
msg="$1";
dir="/tmp/"
tmpfile="sms.$$"
cookie=$dir$tmpfile

curl -s -D $cookie http://websms.vodacom.net/vodacom/WebSms/index.html 1>/dev/null 2>/dev/null
curl -s  -d "cellnum=$number&message=$msg&email=&charsLeft=&I2=Send%20SMS" -b $cookie -e -L http://websms.vodacom.net/vodacom/Send 1>/dev/null  

rm $cookie

