.TH MAC-gyver 8
.SH NAME
MAC-gyver \- Half Ethernet Address Translation bridging code
.SH SYNOPSIS
.B MAC-gyver
-i internal_interface -e external_interface [-d] [-f addresses_file]
.br
.B MAC-gyver
-h
.SH DESCRIPTION
.B MAC-gyver
is based on
.B HEAT
tecnology, and allows you to get rid of Cisco Catalyst port security settings.
Just connect your LAN to the internal interface, and the Catalyst on the external one.
.br
You've to write in a file ehternet addresses you want to be processed by HEAT.
.LP
For more info about
.B HEAT
look at
.BR http://www.pkcrew.org/ .
.SH OPTIONS
.TP 
.B -i internal_interface
Specify the internal interface, where your LAN is connected to.
.TP
.B -e external_interface
Specify the external interface, where the Catalyst is.
.TP
.B -d
Turn on debug. It also don't fork into backgrond.
For each packet written to the internal interface it prints a
.BR . ,
for each ono the external interface a
.BR o .
.TP
.B -f addresses_file
.TP
.B -h
Print usage.
Specify which file contains ethernet hardware address to process with HEAT.
.br
Default is /etc/ethernet_hosts.conf.
.SH FILES
/etc/ethernet_hosts.conf
.SH SEE ALSO
.BR A-team (8)
.SH AUTHOR
tHE rECIdjVO <recidjvo@pkcrew.org>
.br
http://www.pkcrew.org/
