# Metadata for Northern Phun Co. (NPC)

slug: "Northern_Phun_Co"
name: "Northern Phun Co."
description: "A bilingual (English/French) underground e-zine from Quebec covering phreaking, hacking, and Canadian telecom systems from 1992-1994."

# ============================================================================
# HISTORICAL CONTEXT
# ============================================================================

years_active: "1992-1994"
publication_frequency: "irregular"

authors:
  - "Phunphreaker"
  - "Various contributors"

groups:
  - "Northern Phun Co."

origin:
  country: "Canada"
  city: "Quebec"
  region: "North America"

# ============================================================================
# CONTENT CLASSIFICATION
# ============================================================================

languages:
  - "en"
  - "fr"

topics:
  - "phreaking"
  - "hacking"
  - "networking"
  - "social_engineering"
  - "tutorials"
  - "hardware"
  - "culture"

technical_level: "intermediate"

# ============================================================================
# SIGNIFICANCE & INFLUENCE
# ============================================================================

significance: |
  Northern Phun Co. was one of the few bilingual underground ezines, reflecting
  Quebec's unique French-English cultural mix. It focused heavily on Canadian
  telecommunications infrastructure, particularly Bell Canada and Quebec phone
  systems, providing region-specific technical information rarely found in
  US-centric ezines.

  The publication documented the transition period from analog to digital phone
  switches in Canada, including detailed technical specifications, switch codes,
  and phreaking techniques specific to Northern Telecom (Nortel) equipment.

  Notable for its detailed diagrams, thorough technical documentation, and
  educational approach rather than purely destructive techniques.

influenced_by:
  - "phrack"
  - "2600"

related_ezines:
  - "2600"
  - "phrack"
  - "p-80"
  - "frhack"

# ============================================================================
# CONTENT SUMMARY
# ============================================================================

typical_content:
  - "Canadian telecommunications system documentation"
  - "Bell Canada and Quebec phone network technical details"
  - "Northern Telecom (Nortel) switch information"
  - "Social engineering techniques for Canadian telcos"
  - "BBS lists and local scene information"
  - "Phreaking tutorials and box building guides"
  - "Hardware hacking projects"
  - "Bilingual articles mixing English and French"

highlights:
  - issue: "npc-005"
    title: "The Telco Story"
    description: "Comprehensive documentation of Canadian telephone system architecture"
  - issue: "npc-008"
    title: "Northern Telecom DMS-100 Switch Guide"
    description: "Detailed technical specifications for DMS-100 digital switches"

# ============================================================================
# QUALITY & PRESERVATION NOTES
# ============================================================================

preservation_notes: |
  Collection appears complete with 15 issues (npc-001 through npc-015).
  Files are in good condition with minimal encoding issues. ASCII art and
  diagrams are well-preserved.

content_warnings:
  - "illegal_techniques"
  - "outdated_information"

# ============================================================================
# METADATA
# ============================================================================

metadata_created: "2026-01-11"
metadata_updated: "2026-01-11"
metadata_version: "1.0"
metadata_source: "manual"
metadata_reviewed: true

# ============================================================================
# TRANSLATIONS
# ============================================================================

translations:
  fr:
    name: "Northern Phun Co."
    description: "Un e-zine underground bilingue du Québec couvrant le phreaking, le hacking et les systèmes de télécommunications canadiens de 1992-1994."
