CLS
LOCATE 6, 44: COLOR 15, 0: PRINT "ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿"
LOCATE 7, 44: COLOR 15, 0: PRINT "³official distros³"
LOCATE 8, 44: COLOR 15, 0: PRINT "ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÂÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿  "
LOCATE 9, 44: COLOR 15, 0: PRINT "³"
LOCATE 9, 46: COLOR 15, 0: PRINT "oFFICIAL HQ"
LOCATE 9, 58: COLOR 15, 0: PRINT "³"
LOCATE 9, 59: COLOR 12, 0: PRINT " "
LOCATE 9, 60: COLOR 15, 0: PRINT "iflashera.8m.com"
LOCATE 9, 76: COLOR 12, 0: PRINT " "
LOCATE 9, 77: COLOR 15, 0: PRINT "³  "
LOCATE 10, 44: COLOR 15, 0: PRINT "ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´  "
LOCATE 11, 44: COLOR 15, 0: PRINT "³ pARADOX BBS ³ epx.no-ip.biz:23 ³  "
LOCATE 12, 44: COLOR 15, 0: PRINT "ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ  "
LOCATE 13, 44: COLOR 15, 0: PRINT "ÚÄÄÄÄÄÄÄ¿                          "
LOCATE 14, 44: COLOR 15, 0: PRINT "³mirrors³                          "
LOCATE 15, 44: COLOR 15, 0: PRINT "ÃÄÄÄÄÄÄÄÁÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿"
LOCATE 16, 44: COLOR 15, 0: PRINT "³ mFS sITE   ³ noplacetohide.da.ru ³"
LOCATE 17, 44: COLOR 15, 0: PRINT "ÃÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´"
LOCATE 18, 44: COLOR 15, 0: PRINT "³ zINE sTORE ³ zine-store.com.ar   ³"
LOCATE 19, 44: COLOR 15, 0: PRINT "ÀÄÄÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ"
LOCATE 7, 12: COLOR 8, 0: PRINT "ÛßßßßßßßÛßßßß"
FOR ret = 1 TO 2000: NEXT ret
LOCATE 7, 25: COLOR 7, 0: PRINT "ÛÛÛÛÛÛÛÛÛ"
FOR ret = 1 TO 2000: NEXT ret
LOCATE 7, 34: COLOR 8, 0: PRINT "ßßßßÜ    "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 7, 62: COLOR 12, 0:   PRINT "                  "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 8, 10: COLOR 8, 0: PRINT "±±Û  ÜÛÜ  Û    "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 8, 25: COLOR 7, 0: PRINT "ÛÛÛÛÛÛ  Û    "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 8, 38: COLOR 8, 0: PRINT " ßÜ  "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 9, 6: PRINT "    "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 9, 10: COLOR 8, 0: PRINT "±±Û   Ûÿ  Û    "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 9, 25: COLOR 7, 0: PRINT "ÛÛÛÛÛÛ  Û      "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 9, 40: COLOR 8, 0: PRINT " Û "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 10, 10: COLOR 8, 0: PRINT "±±Û       ÛÜÜÜÜ"
FOR ret = 1 TO 2000: NEXT ret
LOCATE 10, 25: COLOR 7, 0: PRINT "ÛÛÛÛÛÛÛÛÛ       "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 10, 41: COLOR 8, 0: PRINT "Û  "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 11, 10: COLOR 8, 0: PRINT "±±Û                            Û  "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 12, 10: COLOR 8, 0: PRINT "±±Û    "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 12, 17: COLOR 1, 0:        PRINT "ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ     "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 12, 41: COLOR 8, 0: PRINT "Û  "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 13, 10: COLOR 8, 0: PRINT "±±Û    "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 13, 17: COLOR 7, 0: PRINT "Û"
FOR ret = 1 TO 2000: NEXT ret
LOCATE 13, 18: COLOR 1, 7: PRINT "   iNDUSTRIA      "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 14, 17: COLOR 1, 7: PRINT "ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ"
FOR ret = 1 TO 2000: NEXT ret
LOCATE 13, 41: COLOR 8, 0: PRINT "Û  "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 14, 10: COLOR 8, 0: PRINT "±±Û    "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 14, 41: COLOR 8, 0: PRINT "Û  "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 15, 10: COLOR 8, 0: PRINT "±±Û    "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 15, 17: COLOR 7, 0: PRINT "Û"
FOR ret = 1 TO 2000: NEXT ret
LOCATE 15, 18: COLOR 1, 7: PRINT "   fLASHERA! "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 16, 17: COLOR 1, 7: PRINT "ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ"
FOR ret = 1 TO 2000: NEXT ret
LOCATE 15, 31: COLOR 7, 0: PRINT "ÛÛÛÛÛ"
FOR ret = 1 TO 2000: NEXT ret
LOCATE 15, 37: COLOR 8, 0: PRINT "ÜÜÜ Û  "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 16, 10: COLOR 8, 0: PRINT "±±Û    "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 16, 37: COLOR 8, 0: PRINT "ÚÄ¿ Û  "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 17, 10: COLOR 8, 0: PRINT "±±Û ÜÜ "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 17, 17: COLOR 7, 0: PRINT "ÛÛÛ"
FOR ret = 1 TO 2000: NEXT ret
LOCATE 17, 20: COLOR 1, 7: PRINT " issue #o8    "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 17, 34: COLOR 7, 0: PRINT "ÛÛ "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 17, 37: COLOR 8, 0: PRINT "ÀÄÙ Û  "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 18, 10: COLOR 8, 0: PRINT "±±ÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛ  "
FOR ret = 1 TO 2000: NEXT ret
LOCATE 19, 10: COLOR 8, 0: PRINT "±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±   "
press$ = "( press any key to continue )"
press = LEN(press$)
FOR l = 1 TO press
c = c + 1
COLOR 7: LOCATE 4, press + c: PRINT "_"
COLOR 9: LOCATE 4, press: PRINT LEFT$(press$, l)
FOR ret = 1 TO 10000: NEXT ret
NEXT l
LOCATE 4, press + c: COLOR 23: PRINT "_": COLOR 7
DO: LOOP UNTIL INKEY$ <> ""
CLS
COLOR 15
PRINT "                                 . s t a f f ."
PRINT "                                .  i f # o 8  ."
PRINT ""
PRINT "         .handle.                                .what he make."
PRINT ""
PRINT "         toshi (editor / writer / musician / coder)"
PRINT "         lpk/mfs (writer/coder/art plus plus)"
PRINT ""
PRINT "                                . colaborators ."
PRINT ""
PRINT "         Akr0byt3 (writer)"
PRINT ""
PRINT "                           . active users of paradox ."
PRINT ""
PRINT "         duck0 (uploader / ifreader / support)"
PRINT "         sachiel (unknown)"
PRINT ""
PRINT "                     greetz to all the ppl who make this"
PRINT "                       project get better and better :)"
PRINT ""
COLOR 7
END

